name: Checkmarx SAST Scan
on: [pull_request]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - name: Checkmarx CxFlow Action
          uses: checkmarx-ts/checkmarx-cxflow-github-action@v1.9
    