
name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:

    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        deno: ["v1.x", "canary"]
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - name: Install modules
        uses: npm install

      - name: Run lint
        uses: npm run lint
