name: Snyk Scan
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master
      - dev
      - release-*
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Snyk Scan
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor